export const MOCK_OCCUPATION_SELECT = [
  { key: 1, label: 'Project manager' },
  { key: 2, label: 'Developer' },
  { key: 3, label: 'Designer' },
  { key: 4, label: 'Marketing specialist' },
  { key: 5, label: 'Data analyst' },
  { key: 6, label: 'Sales representative' },
  { key: 7, label: 'Accountant' },
  { key: 8, label: 'Teacher' },
  { key: 9, label: 'Nurse' },
  { key: 10, label: 'Doctor' },
  { key: 11, label: 'Lawyer' },
  { key: 12, label: 'Writer' },
  { key: 13, label: 'Graphic designer' },
  { key: 14, label: 'Architect' },
  { key: 15, label: 'Chef' },
  { key: 16, label: 'Financial analyst' },
  { key: 17, label: 'Human resources manager' },
  { key: 18, label: 'Marketing manager' },
  { key: 19, label: 'Research scientist' },
  { key: 20, label: 'Event planner' },
];
