name: Production Build You App Building

on: workflow_dispatch

env:
  NODE_VERSION: 20.5.0
  JAVA_VERSION: 11.0.20
  RUBY_VERSION: 3.2.2
  ENV: ${{ secrets.ENV_PROD}}
  # USED IN BUILD GRADLE
  ANDROID_ALIAS: ${{ secrets.ANDROID_ALIAS }}
  ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY_STAGING }}
  ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD_STAGING }}
  # ------
  CREDENTIAL_FILE_CONTENT: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
  ANDROID_FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
  IOS_FIREBASE_APP_ID: ${{ secrets.IOS_FIREBASE_APP_ID }}

  # iOS
  EXPORT_METHOD: "app-store"
  EXPORT_OPTIONS: "ios/ExportOptions-Appstore.plist"
  P12_BASE64: ${{ secrets.STAGING_BUILD_CERTIFICATE_BASE64 }}
  MOBILE_PROVISION_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
  CERTIFICATE_PASSWORD: ${{ secrets.STAGING_P12_PASSWORD }}
  # ------

jobs:
  setup:
    name: Build App
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install project dependencies
        run: yarn

      - name: Prepare ENV
        run: |
          echo $ENV | base64 --decode >> ".env"
          echo $ANDROID_SIGNING_KEY | base64 --decode >> "android/app/build-you.jks"
          echo $IOS_GOOGLE_SERVICE_PROD | base64 --decode >> "GoogleService-Info.plist"
          echo $ANDROID_GOOGLE_SERVICE_PROD | base64 --decode >> "google-services.json"
          sed -i '' 's/"adhoc"/"it.buildyou.buildyou AppStore"/g; s/adhoc/"it.buildyou.buildyou AppStore"/g' ios/BuildYou.xcodeproj/project.pbxproj
        shell: bash

      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Prebuild Expo
        run: npx expo prebuild
        shell: bash

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Generate App AAB
        run: |
          echo $CREDENTIAL_FILE_CONTENT > "$RUNNER_TEMP/credential.json"
          export GOOGLE_APPLICATION_CREDENTIALS="$RUNNER_TEMP/credential.json"
          cd android && ./gradlew assembleRelease --no-daemon
          npx firebase-tools \
            appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
            --app $ANDROID_FIREBASE_APP_ID \
            --groups "testers" \
            $( (( $INPUT_DEBUG )) && printf %s '--debug' )
          cd ..

      # #  iOS Build
      # - name: Build Cache
      #   uses: mikehardy/buildcache-action@v2

      # - name: Setup Ruby (bundle)
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: ${{ env.RUBY_VERSION }}
      #     bundler-cache: true

      # - name: Restore Pods cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ios/Pods
      #       ~/Library/Caches/CocoaPods
      #       ~/.cocoapods
      #     key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pods-

      # - name: Install Pods
      #   run: cd ios && pod install --repo-update && cd ..

      # - name: Build IOS App
      #   uses: yukiarrr/ios-build-action@v1.4.0
      #   with:
      #     project-path: ios/BuildYou.xcodeproj
      #     p12-base64: ${{ env.P12_BASE64 }}
      #     mobileprovision-base64: ${{ env.MOBILE_PROVISION_BASE64 }}
      #     code-signing-identity: "iPhone Distribution"
      #     team-id: JWQ9T5PFH2
      #     certificate-password: ${{ env.CERTIFICATE_PASSWORD }}
      #     workspace-path: ios/BuildYou.xcworkspace
      #     scheme: BuildYou
      #     export-method: ${{ env.EXPORT_METHOD }}
      #     export-options: ${{ env.EXPORT_OPTIONS }}
      #     output-path: app.ipa

      # - name: Distrbute Firebase # app id can be found in GoogleService-Info.plist
      #   run: |
      #     echo $CREDENTIAL_FILE_CONTENT > "$RUNNER_TEMP/credential.json"
      #     export GOOGLE_APPLICATION_CREDENTIALS="$RUNNER_TEMP/credential.json"
      #     npx firebase-tools \
      #       appdistribution:distribute app.ipa \
      #       --app $IOS_FIREBASE_APP_ID \
      #       --groups "testers" \
      #       $( (( $INPUT_DEBUG )) && printf %s '--debug' )
      #   shell: bash

      # - name: "Upload app to TestFlight"
      #   uses: apple-actions/upload-testflight-build@v1
      #   with:
      #     app-path: "output.ipa"
      #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
      #     api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
