name: Build You App Building

on: workflow_dispatch

env:
  NODE_VERSION: 20.5.0
  JAVA_VERSION: 11.0.20

jobs:
  setup:
    name: Install NodeJS Dependency
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install project dependencies
        run: yarn

  #  Android Build
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install project dependencies
        run: yarn

      - name: Set up our JDK environment # setup JDK environment: mandatory as we need to build  android project
        uses: actions/setup-java@v3
        with:
          distribution: "zulu" # See 'Supported distributions' for available options
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Prepare ENV
        run: |
          echo "$ENV_PROD" | base64 --decode > ".env"
          cat .env
          echo "$IOS_GOOGLE_SERVICE_PROD" | base64 --decode > "GoogleService-Info.plist"
          cat GoogleService-Info.plist
          echo "$ANDROID_GOOGLE_SERVICE_PROD" | base64 --decode > "google-services.json"
          cat google-services.json
          npx expo prebuild

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Generate App AAB
        run: |
          cd android && ./gradlew bundleRelease --no-daemon

      - name: Sign AAB
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      # - name: Upload artifact to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
      #     serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
      #     groups: testers
      #     file: ${{steps.sign_app.outputs.signedReleaseFile}}

  # #  iOS Build
  # ios-build:
  #   name: IOS Production Build
  #   runs-on: macos-latest
  #   defaults:
  #     run:
  #       working-directory: ios

  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v4

  #     - name: Get yarn cache directory path
  #       id: yarn-cache-dir-path
  #       run: echo "::set-output name=dir::$(yarn cache dir)"
  #     - name: Restore node_modules from cache
  #       uses: actions/cache@v3
  #       id: yarn-cache
  #       with:
  #         path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
  #         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-yarn-

  #     - name: Install dependencies # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
  #       run: yarn install --frozen-lockfile

  #     - name: Setup Ruby (bundle)
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: 3.2.2
  #         bundler-cache: true

  #     - name: Restore Pods cache
  #       uses: actions/cache@v3
  #       with:
  #         path: |
  #           ios/Pods
  #           ~/Library/Caches/CocoaPods
  #           ~/.cocoapods
  #         key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pods-

  #     - name: Install Pods
  #       run: cd ios && pod install --repo-update && cd ..

  #     - name: Build IOS App
  #       uses: yukiarrr/ios-build-action@v1.4.0
  #       with:
  #         project-path: ios/MyApp.xcodeproj
  #         p12-base64: ${{ secrets.IOS_P12_BASE64 }}
  #         mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
  #         code-signing-identity: "iPhone Distribution"
  #         team-id: ${{ secrets.IOS_TEAM_ID }}
  #         certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
  #         workspace-path: ios/MyApp.xcworkspace
  #         scheme: MyApp

  #     - name: "Upload app to TestFlight"
  #       uses: apple-actions/upload-testflight-build@v1
  #       with:
  #         app-path: "output.ipa"
  #         issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
  #         api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
  #         api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
